/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.nekojarashi.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ClientType implements org.apache.thrift.TEnum {
  WINDOWS(0),
  MAC_OS_X(1);

  private final int value;

  private ClientType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ClientType findByValue(int value) { 
    switch (value) {
      case 0:
        return WINDOWS;
      case 1:
        return MAC_OS_X;
      default:
        return null;
    }
  }
}
